[package]
name = "dining_philosophers_async"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = [
    "sync",
    "time",
    "macros",
    "rt-multi-thread",
] }
