repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check formatting
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false