[workspace]
resolver = "2"
members = [
    "5.6_fibonacci",
    "6.8_collatz",
    "8.5_nested_arrays",
    "9.6_geometry",
    "10.7_elevator_events",
    "12.6_expression_evaluation",
    "13.4_generic_logger",
    "14.7_generic_min",
]
